export const DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!;
export const WORKSPACE_ID = process.env.NEXT_PUBLIC_APPWRITE_WORKSPACE_ID!; 
export const TASKS_ID = process.env.NEXT_PUBLIC_APPWRITE_TASKS_ID!; 
export const MEMBERS_ID = process.env.NEXT_PUBLIC_APPWRITE_MEMBERS_ID!;
export const PROJECT = process.env.NEXT_PUBLIC_APPWRITE_PROJECT!;
export const PROJECT_COLLECTION_ID = process.env.NEXT_PUBLIC_APPWRITE_PROJECT_COLLECTION_ID!;
export const IMAGES_BUCKET_ID = process.env.NEXT_PUBLIC_APPWRITE_IMAGE_BUCKET_ID!;